### ISSUE TITLE
Class 'WC_Wallee_Integration' not found

### ISSUE THREAD

**Issue by mzwygart** [pfpayments/woocommerce#6]
I get this error when I navigate to WooCommerce → Settings → PostFinance Checkout
`Fatal error: Uncaught Error: Class 'WC_Wallee_Integration' not found in ***/web/app/plugins/woo-postfinance-checkout/includes/admin/class-wc-postfinancecheckout-admin-settings-page.php:318 Stack trace: #0 ***/web/app/plugins/woo-postfinance-checkout/includes/admin/class-wc-postfinancecheckout-admin-settings-page.php(92): WC_PostFinanceCheckout_Admin_Settings_Page->get_settings() #1 ***/web/wp/wp-includes/class-wp-hook.php(307): WC_PostFinanceCheckout_Admin_Settings_Page->settings_tab('') #2 ***/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #3 ***/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #4 ***/app/plugins/woo-postfinance-checkout/includes/admin/class-wc-postfinancecheckout-admin-settings-page.php on line 318`

I downloaded the last release from this repo and installed it manually

**Comment by mzwygart** [comment]
Thanks!
